### ISSUE TITLE
Plugin not marked @threadSafe

### ISSUE THREAD

**Issue by rreddig** [hbakkum/resolve-parent-version-maven-plugin#3]
Hello,

I just noticed that the plugin causes a lot of warnings when you run it on a (multimodule) project with parallel build. The error is like the one depicted here: https://github.com/hcoles/pitest/issues/388#issue-250591838

Way to reproduce it:
1. create any project with the resolve-parent-plugin
2. run 'mvn clean install -T 2'

Not sure if there is any reason, why it is not marked as thread safe. Especially for large projects this is really helpful to build in parallel.

**Comment by simontunnat** [comment]
This would be helpful for me as well.

**Comment by hbakkum** [comment]
Hi,

Ok - let me just spend some time ensuring that this is fine to do and then I'll make another release if so. Will post another update in here soon.

Cheers,
Hayden

**Comment by hbakkum** [comment]
Hey,

Latest plugin version (0.8) now has threadSafe = true. Please confirm this works for you and I'll close this task.

Cheers,
Hayden

**Comment by newur** [comment]
Hey, thanks for the update. Will test it asap and let you know.

**Comment by newur** [comment]
Tested on a ~550 modules project with different machines. No problems so far. 

Thanks a lot for your awesome work!

**Comment by hbakkum** [comment]
Appreciate the thorough testing.

I'll close this as resolved.

Thanks!
